### ISSUE TITLE
【建议】增加第三方中转API支持

### ISSUE THREAD

**Issue by FINatiend** [zhxiaogg/mychats.app#1]
刚试了下第三方中转api，输入令牌sk-xxxxxxxxx，网站 https://api.xxxx.com/v1 之后，拉取不到模型，（能否增加自定义模型名称？）。建议可以增加第三方api的支持，我身边用第三方api的人很多（主要是便宜），这样在官方mac版应用出来之后MyChats也有用的意义。
最后加一个第三方api调用的例子：
```
curl -k https://api.xxx.com/v1/chat/completions 
-H "Content-Type: application/json" 
-H "Authorization: Bearer sk-xxxxxx（你的令牌）" 
-d '{
"model": "gpt-3.5-turbo",
"messages": 【{"role": "user", "content": "Hello!"}】
}'
```

**Comment by zhxiaogg** [comment]
感谢反馈和建议！接下来打算改一下模型配置的交互逻辑，自定义模型名称是可以支持的。

我比较担心第三方 API 的跟官方的兼容性，请问两者一致么？如果方便的话，最好可以给我看下具体的接口文档或示例代码。

**Comment by FINatiend** [comment]
我使用的api和官方兼容性一致的，我在自己代码中调用过或者沉浸式翻译中使用过。
使用时将https://api.openai.com/v1替换成第三方网站接口URL：https://api.g4f.icu/v1；密钥替换成第三方提供食物密钥；模型名称输入想要的模型名称就行。
这是我使用的第三api的网站：https://api.g4f.icu 在网站的底部有在各种不用应用中调用的说明，基本和我刚刚说的一致。

**Comment by zhxiaogg** [comment]
@FINatiend 新的 v0.2.0 应该已经支持了，可以测试下。

**Comment by FINatiend** [comment]
可以使用了，感谢
